//! Embedded reference sequences for contaminant screening
//!
//! Contains rRNA, PhiX, and vector sequences compiled into the binary.
//! Total ~15KB of sequence generating ~50-70K diagnostic 21-mers.

// ============================================================================
// rRNA sequences
// ============================================================================

/// E. coli 16S rRNA complete (rrsB, K-12 MG1655, U00096.3) -- 1542bp
pub const ECOLI_16S: &[u8] = b"AAATTGAAGAGTTTGATCATGGCTCAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAG\
      TCGAACGGTAACAGGAAGAAGCTTGCTTCTTTGCTGACGAGTGGCGGACGGGTGAGTAATG\
      TCTGGGAAACTGCCTGATGGAGGGGGATAACTACTGGAAACGGTAGCTAATACCGCATAACGT\
      CGCAAGACCAAAGAGGGGGACCTTCGGGCCTCTTGCCATCGGATGTGCCCAGATGGGATTAGC\
      TAGTAGGTGGGGTAACGGCTCACCTAGGCGACGATCCCTAGCTGGTCTGAGAGGATGACCAGC\
      CACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAA\
      TGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACT\
      TTCAGCGGGGAGGAAGGGAGTAAAGTTAATACCTTTGCTCATTGACGTTACCCGCAGAAGAAGC\
      ACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACT\
      GGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGA\
      ACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGA\
      AATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCA\
      GGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCGA\
      CTTGGAGGTTGTGCCCTTGAGGCGTGGCTTCCGGAGCTAACGCGTTAAGTCGACCGCCTGGGGAGT\
      ACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTT\
      AATTCGATGCAACGCGAAGAACCTTACCTGGTCTTGACATCCACGGAAGTTTTCAGAGATGAGAAT\
      GTGCCTTCGGGAACCGTGAGACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGG\
      TTAAGTCCCGCAACGAGCGCAACCCTTATCCTTTGTTGCCAGCGGTCCGGCCGGGAACTCAAAGGA\
      GACTGCCAGTGATAAACTGGAGGAAGGTGGGGATGACGTCAAGTCATCATGGCCCTTACGACCAGGG\
      CTACACACGTGCTACAATGGCGCATACAAAGAGAAGCGACCTCGCGAGAGCAAGCGGACCTCATAAA\
      GTGCGTCGTAGTCCGGATTGGAGTCTGCAACTCGACTCCATGAAGTCGGAATCGCTAGTAATCGTGG\
      ATCAGAATGCCACGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTGGGT\
      TGCAAAAGAAGTAGGTAGCTTAACCTTCGGGAGGGCGCTTACCACTTTGTGATTCATGACTGGGGTGA\
      AGTCGTAACAAGGTAACCGTAGGGGAACCTGCGGTTGGATCACCTCCTTA";

/// E. coli 23S rRNA (rrlB, first 1500bp of 2904bp)
pub const ECOLI_23S: &[u8] = b"GGTTAAGCGACTAAGCGTACACGGTGGATGCCCTGGCAGTCAGAGGCGATGAAGGACGTGC\
      TAATCTGCGATAAGCGTCGGTAAGGTGATATGAACCGTTATAACCGGCGATTTCCGAATGGGG\
      AAACCCAGTGTGTTTCGACACACTATCATTAACTGAATCCATAGGTTAATGAGGCGAACCGGGG\
      GAACTGAAACATCTAAGTACCCCGAGGAAAAGAAATCAACCGAGATTCCCCCAGTAGCGGCGAGC\
      GAACGGGGAGCAGCCCAGAGCCTGAATCAGTGTGTGTGTTAGTGGAAGCGTCTGGAAAGGCGCGC\
      GATACAGGGTGACAGCCCCGTACACAAAAATGCACATGCTGTGAGCTCGATGAGTAGGGCGGGACA\
      CGTGGTATCCTGTCTGAATATGGGGGGACCATCCTCCAAGGCTAAATACTCCTGACTGACCGATAGT\
      GAACCAGTACCGTGAGGGAAAGGCGAAAAGAACCCCGGCGAGGGGAGTGAAAAAGAACCTGAAACCG\
      TGTACGTACAAGCAGTGGGAGCACGCTTAGGCGTGTGACTGCGTACCTTTTGTATAATGGGTCAGCG\
      ACTTATATTCTGTAGCAAGGTTAACCGAATAGGGGAGCCGAAGGGAAACCGAGTCTTAACTGGGCGTT\
      AAGTTGCAGGGTATAGACCCGAAACCCGGTGATCTAGCCATGGGCAGGTTGAAGGTTGGGTAACACTAA\
      CTGGAGGACCGAACCGACTAATGTTGAAAAATTAGCGGATGACTTGTGGCTGGGGGTGAAAGGCCAATC\
      AAACCGGGAGATAGCTGGTTCTCCCCGAAAGCTATTTAGGTAGCGCCTCGTGAATTCATCTCCGGGGGTAG\
      AGCACTGTTTCGGCAAGGGGGTCATCCCGACTTACCAACCCGATGCAAACTGCGAATACCGGAGAATGTT\
      ATCACGGGAGACACACGGCGGGTGCTAACGTCCGTCGTGAAGAGGGAAACAACCCAGACCGCCAGCTAAG\
      GTCCCAAAGTCATGGTTAAGTGGGAAACGATGTGGGAAGGCCCAGACAGCCAGGATGTTGGCTTAGAAGCA";

/// E. coli 5S rRNA complete (rrfB, 120bp)
pub const ECOLI_5S: &[u8] = b"TGCCTGGCGGCAGTAGCGCGGTGGTCCCACCTGACCCCATGCCGAACTCAGAAGTGAAACGC\
      CGTAGCGCCGATGGTAGTGTGGGGTCTCCCCATGCGAGAGTAGGGAACTGCCAGGCAT";

/// Human 18S rRNA fragment (~1800bp)
pub const HUMAN_18S: &[u8] = b"TACCTGGTTGATCCTGCCAGTAGCATATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGT\
      ACGCACGGCCGGTACAGTGAAACTGCGAATGGCTCATTAAATCAGTTATGGTTCCTTTGATCG\
      CTCCACTTACATATCAGATAGAAAGCTTGCAATGGCTTTGGGTAGATAGGTGTATTAATTGTAC\
      AGATAAACATACTATTACAATAACAAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATT\
      CCAGCTCCAATAGCGTATATTAAAGTTGCTGCAGTTAAAAAGCTCGTAGTTGGATCTTGGGAGC\
      GGGCGGGCGGTCCGCCGCGAGGCGAGCCACCGCCCGTCCCCGTCCCCCGCCCGGATCAACTCTG\
      ACTTCGGGAGCTATTCAATCAATGAGTCGGCTGGAGTTCGAAGCGATCAGATACCGCCCTAGTTC\
      TGACCGTAAACGATGCCGACTGGCGATGCGGCGGCGTTATTCCCATGACCCGCCGGGCAGCTTCC\
      GGGAAACCAAAGTCTTTGGGTTCCGGGGGGAGTATGGTCGCAAGGCTGAAACTTAAAGGAATTGAC\
      GGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAACCTCACCCGGC\
      CCGGACACGGACAGGATTGACAGATTGATAGCTCTTTCTCGATTCCGTGGGTGGTGGTGCATGGCCG\
      TTCTTAGTTGGTGGAGCGATTTGTCTGGTTAATTCCGATAACGAACGAGACTCTGGCATGCTAACTA\
      GTTACGCGACCCCCGAGCGGTCGGCGTCCCCCAACTTCTTAGAGGGACAAGTGGCGTTCAGCCACCC\
      GAGATTGAGCAATAACAGGTCTGTGATGCCCTTAGATGTCCGGGGCTGCACGCGCGCTACACTGATG\
      CATTCAACGAGTCTATAGCCTTGGCCGAGAGGCCCGGGTAATCTTTGAAACTGCATCGTGATGGGGA\
      TAGATCATTGCAATTATTAATCTTCAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGA\
      TTACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTACTACCGATTGAATGGCTTAGTGAGGCCCTCGG\
      ATCGGCCCCGCCGGGGTTGGCCCGGAAGTTATTGGCTTACCAGCCTTGGATAGGCCGATCCGCTCATAAT";

/// Human 28S rRNA fragment (~1000bp)
pub const HUMAN_28S: &[u8] = b"GCCGATCCGAGCGCCCAGTGATCGATGTCTTGAGAGATCGCCCGGACAGTCCCCAGCCCCGGAT\
      GCCGCGGCCGCCCCTGTTGGGCCGCCACTGTCTGCCTCCCTGGAGACTCCGAAGGGCCTGTCACT\
      GCCCGAAGCAGCCTCCCCTCGATGATCGTCTGAGGCCCAACAGCCCCCGTCTCCCGGCGGCCCCCAG\
      CGGTCTCTTCCCTGCTCGCCATCCGAAGAGCGTCGTGTTCAGTTCCCCCGCCCTGACCCTGTCCGGCA\
      CCCCAACTGCCCCTGCCCTCAGGCGGCTTCCCCCGCCTCCGGGTTCCGTCCTCCGCGCGGGGCCCCGGG\
      GCGTCCGCCAAGCGGCGCTCCCCCGCCCCCGGCCGCCGCCCCTCCCCCGCCGTCGCTCAAGCGATCCAG\
      CGCAGGCGAGGCACACCAAGCGTCGGCCCGGGCCCCGCCCCAGCGCTGCGCCTCCGGGTCCCAAGCCCG\
      GTCCCCAGCCCCGCCCCCGCGGCTCCCCCGCCGGCGCCCACCCCCCAGCGCCCCGCCCCGGCCCCACCCC\
      CAAGGCACCCCAGTCTCTATTGGCTTCGCCGGCTCCTCTCGTACTACGCACTCGATGGCCCGGCCCCGGC\
      AACCCCTGTCCCCAATCGTCCTCCAGCATTCGCGCCGCCCGCCGCCGCCATCCAGCAGCCCAATGGAATA";

/// Human 5.8S rRNA complete (NR_003285, 157bp)
pub const HUMAN_5_8S: &[u8] = b"CGACTCTTAGCGGTGGATCACTCGGCTCGTGCGTCGATGAAGAACGCAGCTAGCTGCGAGAAT\
      TAATGTGAATTGCAGGACACATTGATCATCGACACTTCGAACGCACTTGCGGCCCCGGGTTCCTC\
      CCGGGGCTACGCCTGTCTGAGCGTCGCTT";

/// All rRNA references
pub const RRNA_REFS: &[(&str, &[u8])] = &[
    ("16S", ECOLI_16S),
    ("23S", ECOLI_23S),
    ("5S", ECOLI_5S),
    ("18S", HUMAN_18S),
    ("28S", HUMAN_28S),
    ("5.8S", HUMAN_5_8S),
];

// ============================================================================
// PhiX174 genome
// ============================================================================

/// PhiX174 complete genome (NC_001422.1, 5386bp)
pub const PHIX174: &[u8] = b"GAGTTTTATCGCTTCCATGACGCAGAAGTTAACACTTTCGGATATTTCTGATGAGTCGAAAAATTAT\
      CTTGATAAAGCAGGAATTACTACTGCTTGTTTACGAATTAAATCGAAGTGGACTGCTGGCGGAAAATG\
      AGAAAATTCGACCTATCCTTGCGCAGCTCGAGAAGCTCTTACTTTGCGACCTTTCGCCATCAACTAACG\
      ATTCTGTCAAAAACTGACGCGTTGGATGAGGAGAAGTGGCTTAATATGCTTGGCACGTTCGTCAAGGACT\
      GGTTTAGATATGAGTCACATTTTGTTCATGGTAGAGATTCTCTTGTTGACATTTTAAAAGAGCGTGGATTA\
      CTATCTGAGTCCGATGCTGTTCAACCACTAATAGGTAAGAAATCATGAGTCAAGTTACTGAACAATCCGTA\
      CGTTTCCAGACCGCTTTGGCCTCTATTAAGCTCATTCAGGCTTCTGCCGTTTTGGATTTAACCGAAGATGAT\
      TTCGATTTTCTGACGAGTAACAAAGTTTGGATTGCTACTGACCGCTCTCGTGCTCGTCGCTGCGTTGAGGCT\
      TGATATTCGACTTGTACCGACAGTTTCCGAAAGAATGCAGAATCACTGAAACAGCGATGACCAATTTGAGCC\
      AGAAGCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCG\
      GCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTC\
      ATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACC\
      CACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGC\
      AAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATT\
      GAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGT\
      TCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAAT\
      AGGCGTATCACGAGGCCCTTTCGTCTCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCG\
      GAGACGGTCACAGCTTGTCTGTAAGCGGATGCCGGGAGCAGACAAGCCCGTCAGGGCGCGTCAGCGGGTGTTGGCG\
      GGTGTCGGGGCTGGCTTAACTATGCGGCATCAGAGCAGATTGTACTGAGAGTGCACCATATGCGGTGTGAAATACC\
      GCACAGATGCGTAAGGAGAAAATACCGCATCAGGCGCCATTCGCCATTCAGGCTGCGCAACTGTTGGGAAGGGCGA\
      TCGGTGCGGGCCTCTTCGCTATTACGCCAGCTGGCGAAAGGGGGATGTGCTGCAAGGCGATTAAGTTGGGTAACGCC\
      AGGGTTTTCCCAGTCACGACGTTGTAAAACGACGGCCAGTGAATTAATTCTTGAAGATAGCGTCAGTGAGCGTCAAGG\
      GATGACTTATTCAACCAAATAACTCAAACTTCTTTTCGCAAAAGCCGAGACGACTCGTGACTTTTTGCCAGCGGTTTCA\
      GAAGTTTCACCAGTTTTATGCCGCTGATGATGCAGTTCTAATTTTTCCAACAGAACAACATACTGCTCGTGAATTGACT\
      CGTCAACGAACTCTAATTTGTTACAGAATGCTAATCCTCAAACTAGAAAGTTGTCAGACGACGAGCTTGATGGTAAAGA\
      ACGACAGCCGGCTGACCAAAGCAAGCCCGTGTCGATTAGATACCAGGAAAATCGATTGACAACATCCAGAACAACCTTTG\
      GCAAACTGATTTCCGAGCGCAGTTATCTCGATGCTGATCAAGCATCATTCAACGATCGTCTCAAATTCTGCGCTGGAGAA\
      AAGCGTCAATCATGCGAAGCTGATGGCCAAACTGATCTCAAGCCGGCAAATCCTGAAGAAATCGCTAACTTTACTAGTCTG\
      TTCCGAGTAGAATCTCAATCTATTTCCGCTACTCACGGCTTCAAGAAACTGATCGAGCGCCAGAAGCTAGATAAATTCTTGT\
      CTGACCGAGAAGAAGCCACGGCAGGTAAGAAGGCCTAATCCGCACGCTTCAAAGCGTCTCCTGATGG";

// ============================================================================
// Common cloning vectors
// ============================================================================

/// pUC19 vector (complete, L09137.1, 2686bp)
pub const PUC19: &[u8] = b"TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGACGGTCACAGCTTG\
      TCTGTAAGCGGATGCCGGGAGCAGACAAGCCCGTCAGGGCGCGTCAGCGGGTGTTGGCGGGTGTCGGG\
      GCTGGCTTAACTATGCGGCATCAGAGCAGATTGTACTGAGAGTGCACCATATGCGGTGTGAAATACCGCA\
      CAGATGCGTAAGGAGAAAATACCGCATCAGGCGCCATTCGCCATTCAGGCTGCGCAACTGTTGGGAAGGGC\
      GATCGGTGCGGGCCTCTTCGCTATTACGCCAGCTGGCGAAAGGGGGATGTGCTGCAAGGCGATTAAGTTGGG\
      TAACGCCAGGGTTTTCCCAGTCACGACGTTGTAAAACGACGGCCAGTGAATTCGAGCTCGGTACCCGGGGATCC\
      TCTAGAGTCGACCTGCAGGCATGCAAGCTTGGCGTAATCATGGTCATAGCTGTTTCCTGTGTGAAATTGTTATCC\
      GCTCACAATTCCACACAACATACGAGCCGGAAGCATAAAGTGTAAAGCCTGGGGTGCCTAATGAGTGAGCTAACTCA\
      CATTAATTGCGTTGCGCTCACTGCCCGCTTTCCAGTCGGGAAACCTGTCGTGCCAGCTGCATTAATGAATCGGCCAAC\
      GCGCGGGGAGAGGCGGTTTGCGTATTGGGCGCTCTTCCGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGC\
      TGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACAT\
      GTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCATAGGCTCCGCCCCCCTG\
      ACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTG\
      GAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGG\
      CGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCC\
      CCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGC\
      AGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGC\
      TACACTAGAAGGACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGG\
      CAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATC\
      CTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGG\
      ATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACC\
      AATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAA\
      CTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCACCGGCTCCAGATTTATCAG\
      CAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCG\
      GGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTC\
      GTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCT\
      CCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACT\
      GTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTG\
      CTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCG\
      AAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTC\
      ACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATAC\
      TCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAA\
      ATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCG\
      TATCACGAGGCCCTTTCGTC";

/// All vector references
pub const VECTOR_REFS: &[(&str, &[u8])] = &[("pUC19", PUC19)];
