//! QC modules — each implements dual QA/QC (action + reporting)

mod adapter;
mod complexity;
mod contaminant;
mod contaminant_refs;
pub mod dedup;
pub mod host;
mod length;
pub mod merge;
mod nfilter;
mod polyx;
pub mod qa_stats;
mod quality;

pub use adapter::AdapterTrimmer;
pub use complexity::ComplexityFilter;
pub use contaminant::ContaminantScreener;
pub use host::HostFilter;
pub use length::LengthFilter;
pub use merge::{MergeConfig, MergeResult, ReadMerger};
pub use nfilter::NFilter;
pub use polyx::PolyXTrimmer;
pub use qa_stats::{AnalyticsSnapshot, QaStatsCollector, QaStatsSnapshot, ReadAnalytics};
pub use quality::QualityTrimmer;

use crate::pipeline::AnnotatedRecord;
use serde::{Deserialize, Serialize};
use std::sync::atomic::{AtomicU64, Ordering};

/// Report generated by a QC module
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModuleReport {
    /// Module name
    pub name: String,
    /// Number of reads processed by this module
    pub reads_processed: u64,
    /// Number of reads failed/removed by this module
    pub reads_removed: u64,
    /// Number of reads modified (trimmed) by this module
    pub reads_modified: u64,
    /// Total bases removed by this module
    pub bases_removed: u64,
    /// Module-specific additional metrics
    pub extra: serde_json::Value,
}

/// Trait for QC modules. Each module processes reads and reports metrics.
///
/// Modules must be Send + Sync for Rayon parallel processing.
/// Internal metrics use atomics for thread-safe accumulation.
pub trait QcModule: Send + Sync {
    /// Process a single annotated read
    fn process(&self, record: &mut AnnotatedRecord);

    /// Generate aggregate report for this module
    fn report(&self) -> ModuleReport;

    /// Module name (used in passport and logging)
    fn name(&self) -> &str;
}

/// Thread-safe counter for module statistics
pub(crate) struct AtomicStats {
    pub reads_processed: AtomicU64,
    pub reads_removed: AtomicU64,
    pub reads_modified: AtomicU64,
    pub bases_removed: AtomicU64,
}

impl AtomicStats {
    pub fn new() -> Self {
        Self {
            reads_processed: AtomicU64::new(0),
            reads_removed: AtomicU64::new(0),
            reads_modified: AtomicU64::new(0),
            bases_removed: AtomicU64::new(0),
        }
    }

    pub fn record_processed(&self) {
        self.reads_processed.fetch_add(1, Ordering::Relaxed);
    }

    pub fn record_removed(&self) {
        self.reads_removed.fetch_add(1, Ordering::Relaxed);
    }

    pub fn record_modified(&self, bases_removed: usize) {
        self.reads_modified.fetch_add(1, Ordering::Relaxed);
        self.bases_removed
            .fetch_add(bases_removed as u64, Ordering::Relaxed);
    }

    pub fn to_report(&self, name: &str, extra: serde_json::Value) -> ModuleReport {
        ModuleReport {
            name: name.to_string(),
            reads_processed: self.reads_processed.load(Ordering::Relaxed),
            reads_removed: self.reads_removed.load(Ordering::Relaxed),
            reads_modified: self.reads_modified.load(Ordering::Relaxed),
            bases_removed: self.bases_removed.load(Ordering::Relaxed),
            extra,
        }
    }
}
