//! HTML report generator -- self-contained single-file QC dashboard
//!
//! Embeds the React + shadcn/ui + Recharts application (built by Vite)
//! as inlined CSS and JS within a single HTML file. The passport JSON
//! is embedded as a <script type="application/json"> tag that the
//! React app reads at boot.

use crate::report::Passport;
use anyhow::Result;
use std::path::Path;

/// Pre-built React report assets (generated by `cd report-ui && npx vite build`)
const REPORT_CSS: &str = include_str!("../../report-ui/dist/report.css");
const REPORT_JS: &str = include_str!("../../report-ui/dist/report.js");

/// Generate a self-contained HTML report from a passport
pub fn generate_html_report(passport: &Passport, output_path: &Path) -> Result<()> {
    let passport_json = serde_json::to_string(passport)?;
    let sample_name = passport
        .provenance
        .as_ref()
        .and_then(|p| p.input_files.first())
        .map(|f| {
            f.path
                .rsplit('/')
                .next()
                .unwrap_or(&f.path)
                .trim_end_matches(".gz")
                .trim_end_matches(".fastq")
                .trim_end_matches(".fq")
                .to_string()
        })
        .unwrap_or_else(|| "Sample".into());

    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>virome-qc Report - {sample_name}</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet">
<style>{css}</style>
</head>
<body>
<div id="root"></div>
<script type="application/json" id="passport-data">{passport_json}</script>
<script>{js}</script>
</body>
</html>"#,
        sample_name = sample_name,
        css = REPORT_CSS,
        passport_json = passport_json,
        js = REPORT_JS,
    );
    std::fs::write(output_path, html)?;
    Ok(())
}

/// Generate a batch HTML report from multiple passports
pub fn generate_batch_html_report(passports: &[Passport], output_path: &Path) -> Result<()> {
    let batch_json = serde_json::to_string(passports)?;

    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>virome-qc Batch Report</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet">
<style>{css}</style>
</head>
<body>
<div id="root"></div>
<script type="application/json" id="passport-data">{batch_json}</script>
<script>{js}</script>
</body>
</html>"#,
        css = REPORT_CSS,
        batch_json = batch_json,
        js = REPORT_JS,
    );
    std::fs::write(output_path, html)?;
    Ok(())
}
