#!/usr/bin/env python3
"""
Curate non-retroviral EVE reference sequences for virome-qc.

Downloads endogenous and exogenous reference sequences for Bornaviridae,
Parvoviridae, and Filoviridae. Outputs a Rust source file with embedded
byte sequences for compilation into the virome-qc binary.

Endogenous sequences are from known human EVE loci (literature-curated).
Exogenous sequences are RefSeq references for the circulating viruses.

Usage:
    python curate_eve_references.py --output src/modules/eve_sequences.rs
"""

import argparse
import urllib.request
import sys
import time


# Curated accession lists with annotations
# Sources: Horie et al. 2010 (bornaviruses), Belyi et al. 2010 (parvo/filo)

FAMILIES = {
    "Bornaviridae": {
        "description": "Endogenous bornavirus-like elements (EBLs) and exogenous references",
        "exogenous": {
            "NC_001607.1": "Borna_disease_virus_1",          # BoDV-1 (8.9 kb)
            "NC_024781.1": "Variegated_squirrel_bornavirus",  # VSBV-1
        },
        # EBLN loci are too diverged from modern bornaviruses for direct RefSeq accessions.
        # Use the exogenous references for k-mer screening — reads from EBLNs will match
        # with lower containment due to ~60% identity, and the CpG depletion signal
        # will correctly classify them as endogenous.
        "endogenous_note": "EBLNs are ~60% diverged; screened via exogenous k-mers + CpG classification",
    },
    "Parvoviridae": {
        "description": "Endogenous parvoviral elements (EPVs) and exogenous references",
        "exogenous": {
            "NC_000883.2": "Human_parvovirus_B19",  # B19 (5.6 kb)
            "NC_002077.1": "Adeno_associated_virus_2",  # AAV-2 (4.7 kb)
            "NC_001401.2": "Adeno_associated_virus",     # AAV (4.7 kb)
        },
        "endogenous_note": "EPVs are ancient (>40 My); screened via exogenous k-mers + CpG classification",
    },
    "Filoviridae": {
        "description": "Endogenous filoviral element and exogenous references",
        "exogenous": {
            "NC_002549.1": "Ebola_virus_Zaire",     # EBOV (18.9 kb)
            "NC_001608.3": "Marburg_virus",          # MARV (19.1 kb)
        },
        "endogenous_note": "One known endogenous filovirus-like element on chr19",
    },
}


def fetch_sequence(accession: str, name: str, max_retries: int = 3) -> tuple[str, str] | None:
    """Fetch a sequence from NCBI."""
    url = (
        f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
        f"?db=nucleotide&id={accession}&rettype=fasta&retmode=text"
    )

    for attempt in range(max_retries):
        try:
            response = urllib.request.urlopen(url, timeout=30)
            fasta = response.read().decode("utf-8")
            lines = fasta.strip().split("\n")
            seq = "".join(lines[1:]).upper()
            if len(seq) < 100:
                print(f"  WARNING: {accession} returned only {len(seq)} bp", file=sys.stderr)
                return None
            print(f"  {accession} ({name}): {len(seq):,} bp")
            return name, seq
        except Exception as e:
            if attempt < max_retries - 1:
                print(f"  Retry {attempt + 1} for {accession}: {e}", file=sys.stderr)
                time.sleep(2)
            else:
                print(f"  FAILED: {accession} ({name}): {e}", file=sys.stderr)
                return None


def write_rust_source(families: dict, sequences: dict, output_path: str):
    """Generate Rust source file with embedded sequences organized by family."""
    total_seqs = sum(len(seqs) for seqs in sequences.values())
    total_bp = sum(len(s) for seqs in sequences.values() for _, s in seqs)

    with open(output_path, "w") as f:
        f.write("//! Non-retroviral EVE reference sequences for virome-qc\n")
        f.write("//!\n")
        f.write("//! Generated by scripts/curate_eve_references.py\n")
        f.write(f"//! {total_seqs} sequences across {len(sequences)} families, {total_bp:,} bp total\n")
        f.write("//!\n")
        f.write("//! These references enable detection and classification of non-retroviral\n")
        f.write("//! endogenous viral elements (EVEs) using the same three-signal approach\n")
        f.write("//! (CpG depletion + MinHash + ORF integrity) as the retroviral classifier.\n")
        f.write("//!\n")
        f.write("//! Families:\n")
        for family_name, info in families.items():
            n = len(sequences.get(family_name, []))
            f.write(f"//!   - {family_name}: {n} sequences ({info['description']})\n")
        f.write("\n")

        for family_name in families:
            seqs = sequences.get(family_name, [])
            if not seqs:
                continue

            const_name = family_name.upper().replace(" ", "_")
            family_bp = sum(len(s) for _, s in seqs)

            f.write(f"/// {family_name} reference sequences ({len(seqs)} sequences, {family_bp:,} bp)\n")
            f.write(f"pub const {const_name}: &[(&str, &[u8])] = &[\n")

            for name, seq in seqs:
                f.write(f'    ("{name}",\n')
                f.write(f'     b"')
                for i in range(0, len(seq), 80):
                    chunk = seq[i:i + 80]
                    if i > 0:
                        f.write("\\\n       ")
                    f.write(chunk)
                f.write('"),\n')

            f.write("];\n\n")

        # Write a combined constant for unified screening
        f.write("/// All non-retroviral EVE sequences (for unified k-mer screening index)\n")
        f.write("pub const ALL_EVE_SEQUENCES: &[(&str, &[u8])] = &[\n")
        for family_name in families:
            for name, seq in sequences.get(family_name, []):
                f.write(f'    ("{family_name}:{name}",\n')
                f.write(f'     b"')
                for i in range(0, len(seq), 80):
                    chunk = seq[i:i + 80]
                    if i > 0:
                        f.write("\\\n       ")
                    f.write(chunk)
                f.write('"),\n')
        f.write("];\n")

    print(f"\nRust source: {output_path}")
    print(f"  {total_seqs} sequences, {total_bp:,} bp across {len(sequences)} families")


def main():
    parser = argparse.ArgumentParser(description="Curate non-retroviral EVE references")
    parser.add_argument("--output", default="src/modules/eve_sequences.rs",
                        help="Output Rust source file")
    args = parser.parse_args()

    sequences = {}

    for family_name, info in FAMILIES.items():
        print(f"\n=== {family_name} ===")
        print(f"  {info['description']}")
        family_seqs = []

        for acc, name in info["exogenous"].items():
            result = fetch_sequence(acc, name)
            if result:
                family_seqs.append(result)
            time.sleep(0.5)  # NCBI rate limiting

        sequences[family_name] = family_seqs
        print(f"  Total: {len(family_seqs)} sequences")

    write_rust_source(FAMILIES, sequences, args.output)


if __name__ == "__main__":
    main()
